apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: two-tier-ns
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      #nodePort: 31000 # Choose a port number in the range 30000-32767
