apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: two-tier-ns
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/volumes
